I12 genericize exclude models
scientist-softserv/iiif_print pull request #41
Opened 2022-12-16 18:04 UTC by kirkkwang

- add configuration to `#exclude_models`
- update specs
- update config template

2022-12-19 17:02 UTC, ShanaLMoore commented on lib/generators/iiif_print/templates/config/initializers/iiif_print.rb
> +  #   # config.model_name_solr_field_values = ['Generic Work']
Does this mean that generic work would excluded?

2022-12-21 12:53 UTC, jeremyf commented on lib/generators/iiif_print/templates/config/initializers/iiif_print.rb
> +  #   # config.excluded_model_names = [Generic Work, Image]
```suggestion
  #   # config.excluded_model_names = ["Generic Work", "Image"]
```

2022-12-21 12:54 UTC, jeremyf commented on spec/search_builders/custom_search_builder_spec.rb
> +        IiifPrint.config.excluded_model_names = [ExcludedModel, AnotherExcludedModel]
```suggestion
        IiifPrint.config.excluded_model_names = ["Excluded Model Name", "Another Excluded Model"]
```

2022-12-21 12:55 UTC, jeremyf commented on spec/search_builders/custom_search_builder_spec.rb
> +          include("-has_model_ssim:\"ExcludedModel\"", "-has_model_ssim:\"AnotherExcludedModel\"")
```suggestion
          include("-has_model_ssim:\"Excluded Model Name\"", "-has_model_ssim:\"Another Excluded Model\"")
```

2022-12-21 12:57 UTC, jeremyf requested changes
I made some suggestions to change the names to reflect that they are strings and not classes.

2022-12-21 16:46 UTC, ShanaLMoore approved these changes

2022-12-21 17:47 UTC, jeremyf commented on app/search_builders/concerns/iiif_print/exclude_models.rb
>      def exclude_models(solr_parameters)
```suggestion
    def exclude_models(solr_parameters, config: IiifPrint.config)
```

2022-12-21 17:49 UTC, jeremyf commented on spec/search_builders/custom_search_builder_spec.rb
> +        subject.exclude_models(solr_parameters)
```suggestion
        config = IiifPrint::Configuration.new.tap { |c| c.excluded_model_name_solr_field_values = ['Excluded Model', 'Another Excluded Model'] }
        subject.exclude_models(solr_parameters, config: config)
```

2022-12-21 17:52 UTC, jeremyf requested changes
By setting the config in the before block, if we run specs in random order, sometimes they will fail because we're making assumptions about the default configuration.  Instead favor either:

1. Dependency injection of the configuration for this method (as partially suggested)
2. Favor an around spec block that captures the initial global config, changes the global config, runs the test, and then restores the global config.

I strongly advise going with option 1.

2022-12-21 20:05 UTC, jeremyf commented on spec/search_builders/custom_search_builder_spec.rb
> +          byebug
Please remove this

2022-12-21 20:42 UTC, jeremyf approved these changes

2022-12-21 21:10 UTC, merged